spring:
  application:
    name: sundial
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.103/sundial?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: qwer
server:
  port: 9091

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: sundial.entity
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

zkIp: 192.168.1.103:2181